name: Build Windows Executable

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build exe with launcher
    runs-on: windows-latest

    env:
      PYTHONIOENCODING: 'UTF-8'

    strategy:
      matrix:
        python-version: [ 3.12 ]

    steps:
      - name: Configure git
        run: |
          [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
          git config --global core.autocrlf false
          git config --global core.eol lf
          git config --global user.email "BloodLetters45@gmail.com"
          git config --global user.name "BloodLetters"
          echo "action_state=yellow" >> $env:GITHUB_ENV
          echo "${{ env.action_state }}"

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full tag history is available

      - name: Get Latest Tag
        id: tagName
        uses: olegtarasov/get-tag@v2.1.3

      - name: Get Changes between Tags
        id: changes
        uses: simbo/changes-between-tags-action@v1
        with:
          include-hashes: false
          validate-tag: true

      - name: Show Changes
        run: echo "Changes: ${{ steps.changes.outputs.changes }}"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Copy ok-script lib
        run: python -m ok.update.copy_ok_folder

      - name: Rename .py files to .pyx
        run: |
          Get-ChildItem -Path .\src -Recurse -Filter *.py -Exclude '__init__.py' | `
          ForEach-Object { Rename-Item $_.FullName -NewName ($_.FullName -replace '\.py$', '.pyx') }

      - name: Build Cython
        run: |
          python setup.py build_ext --inplace
          Get-ChildItem -Path .\src -Recurse -Filter *.pyx | ForEach-Object { Remove-Item $_.FullName }
          Get-ChildItem -Path .\src -Recurse -Filter *.cpp | ForEach-Object { Remove-Item $_.FullName }

      - name: Run tests
        run: |
          Get-ChildItem -Path ".\tests\*.py" | ForEach-Object {
            Write-Host "Running tests in $($_.FullName)"
            python -m unittest $_.FullName
          }

      - name: Build Executable
        run: |
          echo "Tag: ${{ steps.tagName.outputs.tag }}"
          echo "Changes: ${{ steps.changes.outputs.changes }}"
          
          python -m ok.update.package_launcher ${{ steps.tagName.outputs.tag }} deploy.txt
          Copy-Item -Path "dist" -Destination "gathering-wives" -Recurse
          7z a -t7z -r "gathering-wives-${{ steps.tagName.outputs.tag }}.7z" "gathering-wives"
          Remove-Item -Path "gathering-wives" -Recurse -Force
        shell: pwsh

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: |
            gathering-wives-CPU-full (AMD or other GPUs)
            **Updates:**
            ${{ steps.changes.outputs.changes }}
          draft: false
          prerelease: true
          files: |
            gathering-wives-${{ steps.tagName.outputs.tag }}.7z

      - name: Push to Repo
        run: |
          python -m ok.update.push_repos \
          --repos https://BloodLetters:${{ secrets.GH_TOKEN }}@github.com/BloodLetters/Gathering-Wives \
          --files deploy.txt \
          --tag ${{ steps.tagName.outputs.tag }}
